2: attempt to address the following error in the workflow run: ``` Run echo "DJANGO_SECRET_KEY=123" > .env   echo "DJANGO_SECRET_KEY=123" > .env
  # Using the `-m` flag to run this python command
  # will add the current directory to `sys.path`.
  # python -m pytest
  PYTHONPATH=. pytest \
      --cov=src/ \
      --cov-report=term-missing \
      --cov-branch \
      > line-with-the-TOTAL.txt

  read -r -a arr <<< $(grep TOTAL line-with-the-TOTAL.txt)
  coverage_percentage=${arr[5]}

  echo "coverage-percentage=${coverage_percentage}" >> $GITHUB_OUTPUT
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.3/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.8.3/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.3/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.3/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.3/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.3/x64/lib
Error: Process completed with exit code 2.
```